# -*- coding: utf-8 -*-
"""Graph-Based Data Modeling and Query System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rko5jm8O4w8VnE7Yci--xgMM7jfGjgy3
"""

# =============================================================================
# CELL 1: INSTALLATION & IMPORTS
# =============================================================================

# Install required libraries silently
import subprocess
import sys

packages = [
    "pandas",
    "networkx",
    "pyvis",
    "ipywidgets",
    "google-generativeai",
    "requests"
]

for package in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

# Import libraries
import os
import zipfile
import pandas as pd
import networkx as nx
from pyvis.network import Network
import IPython.display
import ipywidgets as widgets
from google.colab import userdata
import requests
import re
import json

print("Installation complete. All libraries imported.")

# =============================================================================
# CELL 2: DATA EXTRACTION & LOADING
# =============================================================================

# Configuration
ZIP_FILE_PATH = '/content/sap-order-to-cash-dataset.zip'
EXTRACT_DIR = '/content/sap-dataset'
DATA_DIR = os.path.join(EXTRACT_DIR, 'sap-o2c-data')

# 1. Extract Dataset
if not os.path.exists(DATA_DIR):
    if os.path.exists(ZIP_FILE_PATH):
        os.makedirs(EXTRACT_DIR, exist_ok=True)
        with zipfile.ZipFile(ZIP_FILE_PATH, 'r') as zip_ref:
            zip_ref.extractall(EXTRACT_DIR)
        print(f"Dataset extracted to {DATA_DIR}")
    else:
        raise FileNotFoundError("Error: sap-order-to-cash-dataset.zip not found in /content/. Please upload it.")
else:
    print("Dataset already extracted. Skipping extraction.")

# 2. Load Data Helper
def load_jsonl_data(subdirectory_name):
    """Loads all .jsonl files from a specified subdirectory."""
    full_path = os.path.join(DATA_DIR, subdirectory_name)
    if not os.path.exists(full_path):
        print(f"Warning: Directory not found: {full_path}")
        return pd.DataFrame()

    jsonl_files = [os.path.join(full_path, f) for f in os.listdir(full_path) if f.endswith('.jsonl')]
    if not jsonl_files:
        print(f"Warning: No .jsonl files found in {full_path}")
        return pd.DataFrame()

    try:
        df_list = [pd.read_json(f, lines=True) for f in jsonl_files]
        return pd.concat(df_list, ignore_index=True)
    except Exception as e:
        print(f"Error loading {subdirectory_name}: {e}")
        return pd.DataFrame()

# 3. Load Core DataFrames
print("Loading data...")
df_orders = load_jsonl_data('sales_order_headers')
df_items = load_jsonl_data('sales_order_items')
df_billing = load_jsonl_data('billing_document_headers')
df_journal = load_jsonl_data('journal_entry_items_accounts_receivable')

# Verify Load
print(f"Orders: {len(df_orders)} rows")
print(f"Items: {len(df_items)} rows")
print(f"Billing: {len(df_billing)} rows")
print(f"Journal: {len(df_journal)} rows")

if df_orders.empty or df_items.empty:
    raise ValueError("Critical Error: Core datasets are empty. Check extraction.")

# =============================================================================
# CELL 3: GRAPH CONSTRUCTION — TOOLTIP DATA AS JSON (not HTML strings)
# =============================================================================
# KEY CHANGE: Instead of storing HTML in `title`, we store a JSON string in
# a custom attribute `tooltip_data`. Cell 5's JS click handler reads this and
# builds the popup entirely in the browser — zero escaping issues.
# =============================================================================

G = nx.DiGraph()

COLORS = {
    'Customer':     '#1e88e5',
    'Order':        '#ff7043',
    'LineItem':     '#66bb6a',
    'Product':      '#ffee58',
    'Invoice':      '#ab47bc',
    'JournalEntry': '#26a69a'
}

def _val(v):
    if v is None: return None
    s = str(v).strip()
    if s in ('', 'nan', 'None', 'NaT'): return None
    if 'T00:00:00' in s: s = s.split('T')[0]
    return s

def make_tooltip_data(entity_type, fields_dict, connections=0):
    """
    Returns a JSON string encoding the tooltip data.
    This is stored as the node `title` — plain text, no HTML — so PyVis
    cannot mangle it. The JS click handler in Cell 5 parses it and
    renders the card entirely in the browser DOM.
    """
    rows = []
    for label, raw in fields_dict.items():
        v = _val(raw)
        if v is not None:
            rows.append({"k": label, "v": v})
    data = {"type": entity_type, "rows": rows, "connections": connections}
    # Use json.dumps — result is a plain ASCII-safe string vis.js stores as-is
    return json.dumps(data, ensure_ascii=True)

import json

print("Building graph nodes and edges...")

# 1. Customers
if not df_orders.empty:
    for cust_id_val, grp in df_orders.groupby('soldToParty'):
        cid = f"Cust_{cust_id_val}"
        G.add_node(cid,
            label='Customer', type='Customer', color=COLORS['Customer'],
            title=make_tooltip_data('Customer', {
                'Customer ID': cust_id_val,
                'Total Orders': len(grp),
            }, connections=len(grp))
        )

# 2. Orders
for _, r in df_orders.iterrows():
    oid = f"Order_{r['salesOrder']}"
    item_cnt = len(df_items[df_items['salesOrder'] == r['salesOrder']]) if not df_items.empty else 0
    G.add_node(oid,
        label=f"Order {r['salesOrder']}", type='Order', color=COLORS['Order'],
        amount=r['totalNetAmount'],
        title=make_tooltip_data('Sales Order', {
            'Sales Order':  r.get('salesOrder'),
            'Company Code': r.get('companyCode'),
            'Sales Org':    r.get('salesOrganization'),
            'Order Type':   r.get('salesOrderType'),
            'Net Amount':   f"{r.get('totalNetAmount','')} {r.get('transactionCurrency','')}",
            'Created On':   r.get('creationDate'),
            'Customer':     r.get('soldToParty'),
        }, connections=item_cnt + 1)
    )
    G.add_edge(f"Cust_{r['soldToParty']}", oid, relationship='PLACED')

# 3. Line Items & Products
product_usage = df_items['material'].value_counts().to_dict() if not df_items.empty else {}

for _, r in df_items.iterrows():
    iid = f"Item_{r['salesOrder']}_{r['salesOrderItem']}"
    pid = f"Prod_{r['material']}"
    G.add_node(iid,
        label='Item', type='LineItem', color=COLORS['LineItem'],
        title=make_tooltip_data('Order Item', {
            'Sales Order':  r.get('salesOrder'),
            'Item No':      r.get('salesOrderItem'),
            'Material':     r.get('material'),
            'Description':  r.get('materialDescription', r.get('material')),
            'Quantity':     f"{r.get('requestedQuantity','')} {r.get('requestedQuantityUnit','')}",
            'Net Price':    r.get('netPrice'),
            'Plant':        r.get('plant'),
        }, connections=2)
    )
    G.add_node(pid,
        label=f"Prod {r['material']}", type='Product', color=COLORS['Product'],
        title=make_tooltip_data('Product', {
            'Material':    r.get('material'),
            'Description': r.get('materialDescription', r.get('material')),
            'Mat Type':    r.get('materialType'),
            'Mat Group':   r.get('materialGroup'),
            'Base Unit':   r.get('baseUnitOfMeasure'),
            'Used in':     f"{product_usage.get(r['material'], 1)} orders",
        }, connections=product_usage.get(r['material'], 1))
    )
    G.add_edge(f"Order_{r['salesOrder']}", iid, relationship='CONTAINS')
    G.add_edge(iid, pid, relationship='REFERENCES_PRODUCT')

# 4. Invoices
if not df_billing.empty:
    for _, r in df_billing.iterrows():
        bid = f"Bill_{r['billingDocument']}"
        je_c = len(df_journal[df_journal['referenceDocument'] == r['billingDocument']]) if not df_journal.empty else 0
        G.add_node(bid,
            label=f"Inv {r['billingDocument']}", type='Invoice', color=COLORS['Invoice'],
            doc_id=r['billingDocument'],
            title=make_tooltip_data('Billing Document', {
                'Billing Doc':  r.get('billingDocument'),
                'Type':         r.get('billingType'),
                'Company Code': r.get('companyCode'),
                'Billing Date': r.get('billingDate'),
                'Net Amount':   r.get('totalNetAmount'),
                'Tax Amount':   r.get('totalTaxAmount'),
                'Currency':     r.get('transactionCurrency'),
                'Customer':     r.get('soldToParty'),
                'Payer':        r.get('payerParty'),
            }, connections=1 + je_c)
        )
        cust_id = f"Cust_{r['soldToParty']}"
        if cust_id in G:
            G.add_edge(cust_id, bid, relationship='BILLED_TO')

# 5. Journal Entries
if not df_journal.empty:
    for _, r in df_journal.iterrows():
        jid = f"JE_{r['accountingDocument']}"
        G.add_node(jid,
            label=f"JE {r['accountingDocument']}", type='JournalEntry', color=COLORS['JournalEntry'],
            je_id=r['accountingDocument'],
            title=make_tooltip_data('Journal Entry', {
                'CompanyCode':                   r.get('companyCode'),
                'FiscalYear':                    r.get('fiscalYear'),
                'AccountingDocument':            r.get('accountingDocument'),
                'GlAccount':                     r.get('glAccount'),
                'ReferenceDocument':             r.get('referenceDocument'),
                'CostCenter':                    r.get('costCenter'),
                'ProfitCenter':                  r.get('profitCenter'),
                'TransactionCurrency':           r.get('transactionCurrency'),
                'AmountInTransactionCurrency':   r.get('amountInTransactionCurrency'),
                'CompanyCodeCurrency':           r.get('companyCodeCurrency'),
                'AmountInCompanyCodeCurrency':   r.get('amountInCompanyCodeCurrency'),
                'PostingDate':                   r.get('postingDate'),
                'DocumentDate':                  r.get('documentDate'),
                'AccountingDocumentType':        r.get('accountingDocumentType'),
                'AccountingDocumentItem':        r.get('accountingDocumentItem'),
            }, connections=2)
        )
        bill_ref = f"Bill_{r['referenceDocument']}"
        if bill_ref in G:
            G.add_edge(bill_ref, jid, relationship='POSTED_AS')

print(f"Graph Complete: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

# =============================================================================
# CELL 4: GRAPH VISUALIZATION WITH HIGHLIGHTING SUPPORT
# =============================================================================

def create_graph_visualization(graph, max_nodes=300):
    """Creates a PyVis network with highlighting support and returns embeddable HTML."""

    nt = Network(
        height='620px',
        width='100%',
        bgcolor='#000000',
        font_color='#e0e0e0',
        notebook=True,
        directed=True,
        cdn_resources='in_line'
    )

    # Enhanced Physics Options
    nt.set_options("""
    var options = {
        "nodes": {
            "font": {"size": 11, "face": "Arial", "color": "#e0e0e0"},
            "borderWidth": 2,
            "borderColor": "#333333",
            "shadow": {"enabled": true, "color": "rgba(0,0,0,0.5)", "size": 10},
            "shape": "dot",
            "size": 12
        },
        "edges": {
            "color": {"color": "#333333", "highlight": "#3b82f6"},
            "width": 1.5,
            "smooth": false,
            "arrows": {"to": {"enabled": true, "scaleFactor": 0.6}}
        },
        "physics": {
            "forceAtlas2Based": {
                "gravitationalConstant": -60,
                "centralGravity": 0.02,
                "springLength": 120,
                "springConstant": 0.06
            },
            "maxVelocity": 50,
            "solver": "forceAtlas2Based",
            "timestep": 0.35,
            "stabilization": {"iterations": 100}
        },
        "interaction": {
            "hover": true,
            "tooltipDelay": 100,
            "hideEdgesOnDrag": true
        }
    }
    """)

    # Add Nodes (Subset for performance)
    all_nodes = list(graph.nodes(data=True))
    subset = all_nodes[:max_nodes]

    for node_id, attrs in subset:
        nt.add_node(
            node_id,
            label=attrs.get('label', str(node_id))[:20],
            title=attrs.get('title', ''),
            color=attrs.get('color', '#97c2fc'),
            size=16 if attrs.get('type') in ['Customer', 'Order'] else 12,
            borderWidth=2
        )

    # Add Edges
    for source, target, data in graph.edges(data=True):
        if source in nt.get_nodes() and target in nt.get_nodes():
            nt.add_edge(source, target, label=data.get('relationship', ''))

    # Generate HTML string
    html_content = nt.generate_html(notebook=True)
    return html_content

# Generate Visualization
if 'G' in globals():
    graph_html_content = create_graph_visualization(G)
    print(f"Graph visualization generated: {G.number_of_nodes()} nodes processed")
else:
    raise RuntimeError("Graph G not found. Run Cell 3 first.")

# =============================================================================
# CELL 5 (FIXED): FULL GRAPH FILL + ALL PREVIOUS FIXES RETAINED
# =============================================================================

import re, os, base64, json, warnings
import html as html_module
import ipywidgets as widgets
from IPython.display import display, HTML, Javascript
from pyvis.network import Network
import networkx as nx
warnings.filterwarnings('ignore')

try:
    from google.colab import userdata
    API_KEY = userdata.get('GOOGLE_API_KEY')
except Exception:
    API_KEY = None

GRAPH_DIR  = '/content/graph_files'
GRAPH_INIT = os.path.join(GRAPH_DIR, 'graph_init.html')
GRAPH_HI   = os.path.join(GRAPH_DIR, 'graph_highlight.html')
os.makedirs(GRAPH_DIR, exist_ok=True)

highlighted_nodes = []
IFRAME_ID = 'o2c_graph_frame'

# ── POPUP SCRIPT ─────────────────────────────────────────────────────────────

POPUP_SCRIPT = """
<style>
  #node-popup {
    display: none; position: fixed; z-index: 9999;
    top: 16px; right: 16px; width: 252px;
    background: #ffffff;
    border-radius: 12px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.16), 0 1px 4px rgba(0,0,0,0.06);
    border: 1px solid #e5e7eb;
    font-family: 'Segoe UI', system-ui, sans-serif;
    font-size: 12px; overflow: hidden;
    animation: popIn 0.16s cubic-bezier(.4,0,.2,1);
  }
  @keyframes popIn {
    from { opacity:0; transform:translateY(-6px) scale(0.98); }
    to   { opacity:1; transform:none; }
  }
  #node-popup-header {
    padding: 10px 13px 8px;
    display: flex; align-items: center; justify-content: space-between;
    border-bottom: 1px solid #f3f4f6;
  }
  #node-popup-title { font-size:13px; font-weight:700; color:#111827; }
  #node-popup-badge {
    font-size:9px; font-weight:700; padding:2px 7px;
    border-radius:20px; color:#fff; letter-spacing:0.04em;
  }
  #node-popup-close {
    cursor:pointer; color:#9ca3af; font-size:15px;
    line-height:1; margin-left:6px; user-select:none;
  }
  #node-popup-close:hover { color:#374151; }
  #node-popup-body { padding:8px 13px 2px; max-height:320px; overflow-y:auto; }
  #node-popup-body::-webkit-scrollbar { width:3px; }
  #node-popup-body::-webkit-scrollbar-thumb { background:#e5e7eb; border-radius:2px; }
  .popup-row {
    display:flex; gap:8px; padding:3px 0;
    border-bottom:1px solid #f9fafb;
  }
  .popup-row:last-child { border-bottom:none; }
  .popup-key { color:#9ca3af; min-width:86px; flex-shrink:0; font-size:10.5px; padding-top:1px; }
  .popup-val { color:#111827; font-weight:600; font-size:10.5px; word-break:break-all; }
  #node-popup-footer {
    padding:6px 13px 9px; border-top:1px solid #f3f4f6;
    display:flex; align-items:center; justify-content:space-between;
  }
  #node-popup-conn { font-size:11px; color:#2563eb; font-weight:700; }
  #node-popup-hint { font-size:9.5px; color:#d1d5db; font-style:italic; }
</style>

<div id="node-popup">
  <div id="node-popup-header">
    <span id="node-popup-title">Node</span>
    <div style="display:flex;align-items:center;gap:5px">
      <span id="node-popup-badge"></span>
      <span id="node-popup-close"
            onclick="document.getElementById('node-popup').style.display='none'">✕</span>
    </div>
  </div>
  <div id="node-popup-body"></div>
  <div id="node-popup-footer">
    <span id="node-popup-conn"></span>
    <span id="node-popup-hint">Additional fields hidden</span>
  </div>
</div>

<script>
var TYPE_COLORS = {
  'Customer':'#1e88e5','Order':'#ff7043','LineItem':'#66bb6a',
  'Product':'#f59e0b','Invoice':'#ab47bc','JournalEntry':'#26a69a'
};
function showNodePopup(nodeData) {
  var raw = nodeData.title;
  if (!raw) return;
  var data;
  try { data = JSON.parse(raw); } catch(e) { return; }
  var popup = document.getElementById('node-popup');
  document.getElementById('node-popup-title').textContent = data.type || 'Node';
  var badge = document.getElementById('node-popup-badge');
  badge.textContent = data.type || '';
  badge.style.background = TYPE_COLORS[data.type] || '#6b7280';
  var body = document.getElementById('node-popup-body');
  body.innerHTML = '';
  (data.rows || []).forEach(function(row) {
    var div = document.createElement('div');
    div.className = 'popup-row';
    var k = document.createElement('span'); k.className = 'popup-key'; k.textContent = row.k;
    var v = document.createElement('span'); v.className = 'popup-val'; v.textContent = row.v;
    div.appendChild(k); div.appendChild(v);
    body.appendChild(div);
  });
  document.getElementById('node-popup-conn').textContent = 'Connections: ' + (data.connections || 0);
  popup.style.display = 'block';
}
function attachNetworkHandler() {
  if (typeof network === 'undefined') { setTimeout(attachNetworkHandler, 300); return; }
  network.on('click', function(params) {
    if (params.nodes.length > 0) {
      showNodePopup(network.body.data.nodes.get(params.nodes[0]));
    } else {
      document.getElementById('node-popup').style.display = 'none';
    }
  });
}
attachNetworkHandler();
</script>
"""

# ── PYVIS BUILDER (FIXED: full height canvas) ─────────────────────────────────

def build_and_save_pyvis(graph, filepath, highlight_nodes=None):
    nt = Network(
        height='100%', width='100%',
        bgcolor='#ffffff', font_color='#333333',
        notebook=False, directed=True, cdn_resources='remote'
    )
    nt.set_options("""
    var options = {
      "nodes": {
        "font": {"size": 12, "face": "Arial"},
        "borderWidth": 2,
        "shadow": {"enabled": true, "color": "rgba(0,0,0,0.10)", "size": 5}
      },
      "edges": {
        "color": {"color": "#e5e7eb", "highlight": "#2563eb"},
        "width": 1.5, "smooth": false,
        "arrows": {"to": {"enabled": true, "scaleFactor": 0.6}}
      },
      "physics": {
        "forceAtlas2Based": {
          "gravitationalConstant": -80, "centralGravity": 0.02,
          "springLength": 150, "springConstant": 0.05
        },
        "maxVelocity": 50, "solver": "forceAtlas2Based",
        "timestep": 0.35, "stabilization": {"iterations": 150}
      },
      "interaction": {
        "hover": true, "tooltipDelay": 99999,
        "hideEdgesOnDrag": false, "navigationButtons": false
      }
    }
    """)
    subset_ids = list(graph.nodes())[:250]
    for node_id in subset_ids:
        attrs = graph.nodes[node_id]
        is_hi = highlight_nodes and node_id in highlight_nodes
        nt.add_node(
            node_id,
            label=attrs.get('label', str(node_id))[:20],
            title=attrs.get('title', ''),
            color='#ef4444' if is_hi else attrs.get('color', '#97c2fc'),
            size=30 if is_hi else (20 if attrs.get('type') in ['Customer','Order'] else 14),
            borderWidth=3 if is_hi else 2
        )
    added = set(nt.get_nodes())
    for src, tgt, data in graph.edges(data=True):
        if src in added and tgt in added:
            is_hi_e = highlight_nodes and src in highlight_nodes and tgt in highlight_nodes
            nt.add_edge(src, tgt,
                label=data.get('relationship',''),
                color='#ef4444' if is_hi_e else '#e5e7eb',
                width=3 if is_hi_e else 1.5)
    nt.show(filepath, notebook=False)

    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Force full-height canvas — overrides PyVis hardcoded px height
        full_height_css = """
<style>
html, body {
    margin: 0 !important;
    padding: 0 !important;
    width: 100% !important;
    height: 100% !important;
    overflow: hidden !important;
    background: #ffffff !important;
}
#mynetwork {
    width: 100% !important;
    height: 100vh !important;
    min-height: 100% !important;
    position: absolute !important;
    top: 0 !important;
    left: 0 !important;
    right: 0 !important;
    bottom: 0 !important;
}
</style>
"""
        content = content.replace('</head>', full_height_css + '\n</head>')
        content = content.replace('</body>', POPUP_SCRIPT + '\n</body>')

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    return os.path.exists(filepath)


# ── INJECT VIA WIDGET.VALUE (no display() leakage) ───────────────────────────

def inject_graph_into_widget(filepath):
    if not os.path.exists(filepath):
        return
    with open(filepath, 'r', encoding='utf-8') as f:
        html_str = f.read()
    graph_iframe.value = (
        f'<iframe id="{IFRAME_ID}" '
        f'srcdoc="{html_module.escape(html_str)}" '
        f'style="width:100%;height:100%;border:none;background:#fff;'
        f'display:block;position:absolute;top:0;left:0;right:0;bottom:0;" '
        f'sandbox="allow-scripts allow-same-origin">'
        f'</iframe>'
    )


# ── QUERY ENGINE ──────────────────────────────────────────────────────────────

def format_response(sections):
    out = []
    for kind, content in sections:
        if kind == 'heading':
            out.append(f'<div style="font-weight:700;color:#111827;font-size:12px;'
                       f'letter-spacing:0.02em;margin-bottom:6px;padding-bottom:4px;'
                       f'border-bottom:1px solid #e5e7eb;">{content}</div>')
        elif kind == 'row':
            label, val = content
            out.append(f'<div style="display:flex;gap:6px;padding:2px 0;">'
                       f'<span style="color:#6b7280;min-width:80px;flex-shrink:0;font-size:11px;">{label}</span>'
                       f'<span style="color:#111827;font-weight:600;font-size:11px;">{val}</span>'
                       f'</div>')
        elif kind == 'list':
            items = content
            rows = ''.join(
                f'<div style="display:flex;gap:6px;padding:1.5px 0;">'
                f'<span style="color:#6b7280;font-size:11px;min-width:16px;">{i+1}.</span>'
                f'<span style="color:#111827;font-size:11px;">{item}</span></div>'
                for i, item in enumerate(items)
            )
            out.append(rows)
        elif kind == 'status':
            out.append(f'<div style="margin-top:8px;padding:6px 10px;background:#f0f9ff;'
                       f'border:1px solid #bae6fd;border-radius:6px;color:#0369a1;'
                       f'font-size:10.5px;font-weight:600;">'
                       f'◉ {content}</div>')
        elif kind == 'divider':
            out.append('<div style="border-top:1px solid #f3f4f6;margin:6px 0;"></div>')
        elif kind == 'body':
            out.append(f'<div style="color:#374151;font-size:11.5px;line-height:1.6;">{content}</div>')
        elif kind == 'error':
            out.append(f'<div style="color:#dc2626;font-size:11px;">{content}</div>')
    return ''.join(out)


def query_graph_ai(user_query, graph_instance):
    global highlighted_nodes
    highlighted_nodes = []
    q = user_query.lower()

    o2c_keywords = [
        'order','customer','billing','invoice','product','item','sale','sold',
        'qty','amount','journal','entry','document','flow','trace','incomplete',
        'delivery','payment','broken','pending','billed','associated','highest','number'
    ]
    if not any(k in q for k in o2c_keywords):
        return (False, format_response([
            ('body', 'This system answers questions related to the '
                     '<strong>SAP Order-to-Cash dataset</strong> only.'),
            ('divider', ''),
            ('body', 'Try: <em>"Trace order 740506"</em> or <em>"Show broken flows"</em>')
        ]))

    doc_match = re.search(r'\b(\d{6,})\b', q)
    doc_id = doc_match.group(1) if doc_match else None

    # ── TOP PRODUCTS ──
    if 'product' in q and ('highest' in q or 'most' in q or 'top' in q):
        counts = {}
        for node, attrs in graph_instance.nodes(data=True):
            if attrs.get('type') == 'Product':
                related = set()
                for item in graph_instance.predecessors(node):
                    for order in graph_instance.predecessors(item):
                        for cust in graph_instance.predecessors(order):
                            for inv in graph_instance.successors(cust):
                                if 'Bill' in inv: related.add(inv)
                counts[node] = len(related)
        top5 = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
        highlighted_nodes = [p[0] for p in top5]
        sections = [('heading', 'Top Products — Billing Document Association')]
        sections.append(('list', [
            f'<strong>{pid.replace("Prod_","")}</strong> &nbsp;·&nbsp; {cnt} billing documents'
            for pid, cnt in top5
        ]))
        sections.append(('status', f'{len(highlighted_nodes)} product nodes highlighted in RED'))
        return (True, format_response(sections))

    # ── INCOMPLETE FLOWS ──
    if any(k in q for k in ['incomplete','broken','not billed','pending']):
        orders = [n for n,d in graph_instance.nodes(data=True) if d.get('type')=='Order']
        incomplete = []
        for order in orders[:300]:
            custs = [n for n in graph_instance.predecessors(order) if 'Cust' in n]
            if custs and not [n for n in graph_instance.successors(custs[0]) if 'Bill' in n]:
                incomplete.append(order)
        if incomplete:
            highlighted_nodes = incomplete[:15]
            sections = [
                ('heading', 'Incomplete Flow Analysis'),
                ('row', ('Orders without billing', str(len(incomplete)))),
                ('divider', ''),
                ('body', '<strong>Sample orders:</strong>'),
                ('list', [
                    f'<strong>{o.replace("Order_","")}</strong> &nbsp;·&nbsp; '
                    f'Amt: {graph_instance.nodes[o].get("amount","N/A")}'
                    for o in incomplete[:10]
                ]),
                ('status', f'{len(highlighted_nodes)} order nodes highlighted in RED')
            ]
            return (True, format_response(sections))
        return (False, format_response([('body', 'All sampled orders have associated billing documents.')]))

    # ── TRACE ORDER ──
    if ('trace' in q or 'flow' in q) and ('order' in q or doc_id):
        order_id = doc_id
        if not order_id:
            m = re.search(r'order[_\s]*(\d+)', q)
            order_id = m.group(1) if m else None
        if order_id and f"Order_{order_id}" in graph_instance:
            oid = f"Order_{order_id}"
            highlighted_nodes = [oid]
            customers = [n for n in graph_instance.predecessors(oid) if 'Cust' in n]
            cust = customers[0] if customers else None
            if cust: highlighted_nodes.append(cust)
            items = list(graph_instance.successors(oid))
            highlighted_nodes.extend(items[:10])
            products = set()
            for item in items[:10]: products.update(graph_instance.successors(item))
            highlighted_nodes.extend(list(products)[:5])
            invoices = [n for n in graph_instance.successors(cust) if 'Bill' in n] if cust else []
            highlighted_nodes.extend(invoices[:5])
            jes = []
            for inv in invoices[:5]:
                jes.extend(n for n in graph_instance.successors(inv) if 'JE' in n)
            highlighted_nodes.extend(jes[:5])
            attrs = graph_instance.nodes[oid]
            sections = [
                ('heading', f'Flow Trace — Order {order_id}'),
                ('row', ('Net Amount',    str(attrs.get('amount','N/A')))),
                ('row', ('Customer',      cust.replace('Cust_','') if cust else 'N/A')),
                ('divider', ''),
                ('row', ('Line Items',    str(len(items)))),
                ('row', ('Products',      str(len(products)))),
                ('row', ('Invoices',      str(len(invoices)))),
                ('row', ('Journal Entries', str(len(jes)))),
            ]
            if jes:
                sections.append(('row', ('JE Numbers',
                    ', '.join(j.replace('JE_','') for j in jes[:3]))))
            sections.append(('status', f'{len(highlighted_nodes)} nodes highlighted in RED'))
            return (True, format_response(sections))
        return (False, format_response([('error', f'Order {order_id} not found in dataset.')]))

    # ── COUNT ──
    if any(k in q for k in ['count','how many','total']):
        for kw, typ in [('order','Order'),('customer','Customer'),
                        ('invoice','Invoice'),('billing','Invoice'),
                        ('journal','JournalEntry'),('je','JournalEntry')]:
            if kw in q:
                cnt = sum(1 for _,d in graph_instance.nodes(data=True) if d.get('type')==typ)
                return (False, format_response([
                    ('heading', f'Dataset Count — {typ}'),
                    ('row', ('Total records', f'{cnt:,}'))
                ]))

    # ── SPECIFIC DOC LOOKUP ──
    if doc_id:
        for prefix, typ in [('JE_','Journal Entry'),('Bill_','Invoice'),('Order_','Sales Order')]:
            node = f"{prefix}{doc_id}"
            if node in graph_instance:
                highlighted_nodes = [node]
                attrs = graph_instance.nodes[node]
                amt = attrs.get('amount', attrs.get('amountInCompanyCodeCurrency','N/A'))
                sections = [
                    ('heading', f'{typ} — {doc_id}'),
                    ('row', ('Amount', str(amt))),
                    ('status', '1 node highlighted in RED')
                ]
                return (True, format_response(sections))

    return (False, format_response([
        ('body', 'No matching data found. Try one of these:'),
        ('divider', ''),
        ('list', [
            '<em>"Trace order 740506"</em>',
            '<em>"Top products by billing"</em>',
            '<em>"Show broken flows"</em>',
            '<em>"Count all orders"</em>',
        ])
    ]))


# ── CSS ───────────────────────────────────────────────────────────────────────

display(HTML("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700&family=DM+Mono:wght@400;500&display=swap');

.o2c-graph-topbar {
  display:flex; align-items:center; justify-content:space-between;
  padding:13px 20px; border-bottom:1px solid #f3f4f6; background:#fff;
}
.o2c-graph-breadcrumb { font-size:13px; color:#9ca3af; font-family:'Syne',sans-serif; }
.o2c-graph-breadcrumb strong { color:#111827; font-weight:700; }
.o2c-graph-actions { display:flex; gap:8px; }
.o2c-btn {
  font-family:'Syne',sans-serif; font-size:11px; font-weight:600;
  padding:6px 14px; border-radius:6px; border:1px solid #e5e7eb;
  background:#fff; color:#374151; cursor:pointer; transition:all .15s;
}
.o2c-btn:hover { background:#f9fafb; }
.o2c-btn-dark { background:#111827; border-color:#111827; color:#fff; }
.o2c-btn-dark:hover { background:#1f2937; }

.o2c-legend {
  display:flex; gap:14px; padding:7px 20px;
  border-bottom:1px solid #f3f4f6; background:#fafafa; flex-wrap:wrap;
}
.o2c-legend-item {
  display:flex; align-items:center; gap:5px;
  font-size:10px; color:#6b7280; font-weight:500;
  font-family:'Syne',sans-serif; letter-spacing:0.02em;
}
.o2c-legend-dot { width:8px; height:8px; border-radius:50%; flex-shrink:0; }

.o2c-chat-topbar {
  padding:14px 18px 11px; border-bottom:1px solid #f3f4f6; background:#fff;
}
.o2c-chat-eyebrow {
  font-size:9px; font-weight:600; color:#9ca3af;
  text-transform:uppercase; letter-spacing:0.12em; margin-bottom:2px;
  font-family:'Syne',sans-serif;
}
.o2c-chat-title {
  font-size:16px; font-weight:700; color:#111827;
  letter-spacing:-0.02em; font-family:'Syne',sans-serif;
}

.o2c-status {
  display:flex; align-items:center; gap:7px;
  margin:8px 14px; padding:7px 11px;
  background:#ffffff; border:1px solid #e5e7eb; border-radius:7px;
}
.o2c-dot { width:7px; height:7px; border-radius:50%; background:#22c55e; flex-shrink:0; }
.o2c-dot.thinking { background:#f59e0b; animation:blink .9s infinite; }
@keyframes blink { 0%,100%{opacity:1} 50%{opacity:.25} }
.o2c-status-text {
  font-size:10px; color:#6b7280;
  font-family:'DM Mono',monospace; font-weight:500;
}

.o2c-msg {
  display:flex; flex-direction:column;
  padding:0 14px; margin-bottom:10px;
  animation:msgIn .2s ease;
}
@keyframes msgIn { from{opacity:0;transform:translateY(5px)} to{opacity:1;transform:none} }
.o2c-msg.user  { align-items:flex-end; }
.o2c-msg.ai    { align-items:flex-start; }
.o2c-msg-label {
  font-size:9px; color:#c4c9d4; font-weight:600;
  letter-spacing:0.1em; text-transform:uppercase;
  margin-bottom:3px; font-family:'Syne',sans-serif;
}
.o2c-bubble-user {
  padding:9px 12px; border-radius:10px; border-bottom-right-radius:3px;
  font-size:13px; font-weight:500; line-height:1.55; max-width:95%;
  background:#111827; color:#f9fafb;
  font-family:'Syne',sans-serif;
  word-break:break-word;
}
.o2c-bubble-ai {
  padding:10px 13px; border-radius:10px; border-bottom-left-radius:3px;
  font-size:11.5px; line-height:1.6; max-width:98%;
  background:#ffffff; color:#1f2937;
  border:1px solid #e5e7eb;
  font-family:'Syne',sans-serif;
  word-break:break-word;
}
.o2c-textarea-wrap {
  display:flex; gap:8px; align-items:flex-end;
  padding:10px 14px 14px; border-top:1px solid #f3f4f6; background:#fff;
}
</style>
"""))


# ── WIDGETS ───────────────────────────────────────────────────────────────────

# FIXED: graph_iframe — position:absolute iframe + min_height:0 on layout
graph_iframe = widgets.HTML(
    value=f'<iframe id="{IFRAME_ID}" '
          f'style="width:100%;height:100%;border:none;background:#fff;'
          f'display:block;position:absolute;top:0;left:0;right:0;bottom:0;" '
          f'sandbox="allow-scripts allow-same-origin">'
          f'</iframe>',
    layout=widgets.Layout(
        width='100%',
        flex='1',
        overflow='hidden',
        min_height='0',
    )
)

chat_output = widgets.Output(layout={'flex':'1', 'overflow_y':'auto', 'min_height':'0'})

chat_input = widgets.Textarea(
    placeholder='Ask about orders, billing, products…',
    layout=widgets.Layout(
        width='100%', min_height='36px',
        border='1px solid #e5e7eb', border_radius='8px'
    ),
    rows=1
)

send_btn = widgets.Button(
    description='➤',
    layout=widgets.Layout(width='36px', height='36px'),
    style={'button_color': '#111827'}
)

status_w = widgets.HTML("""
<div class="o2c-status">
  <div class="o2c-dot"></div>
  <span class="o2c-status-text">DODGE AI — READY</span>
</div>""")


# ── MESSAGE HELPERS ───────────────────────────────────────────────────────────

def add_message(role, html_content, is_html=False):
    if role == 'You':
        safe = html_module.escape(html_content)
        bubble = f'<div class="o2c-bubble-user">{safe}</div>'
        label  = 'YOU'
        cls    = 'user'
    else:
        bubble = f'<div class="o2c-bubble-ai">{html_content}</div>'
        label  = 'DODGE AI'
        cls    = 'ai'
    with chat_output:
        display(HTML(
            f'<div class="o2c-msg {cls}">'
            f'<div class="o2c-msg-label">{label}</div>'
            f'{bubble}'
            f'</div>'
        ))

def set_status(thinking):
    if thinking:
        status_w.value = ('<div class="o2c-status">'
            '<div class="o2c-dot thinking"></div>'
            '<span class="o2c-status-text">DODGE AI — PROCESSING…</span></div>')
    else:
        status_w.value = ('<div class="o2c-status">'
            '<div class="o2c-dot"></div>'
            '<span class="o2c-status-text">DODGE AI — READY</span></div>')


# ── SEND HANDLER ──────────────────────────────────────────────────────────────

def on_send(b):
    global highlighted_nodes
    query = chat_input.value.strip()
    if not query: return
    chat_input.value = ''
    set_status(True)
    send_btn.disabled = True
    add_message('You', query, is_html=False)
    try:
        has_highlights, html_response = query_graph_ai(query, G)
        add_message('AI', html_response, is_html=True)
        hi = highlighted_nodes if has_highlights and highlighted_nodes else None
        if build_and_save_pyvis(G, GRAPH_HI, highlight_nodes=hi):
            inject_graph_into_widget(GRAPH_HI)
    except Exception as e:
        add_message('AI', f'<div style="color:#dc2626;font-size:11px;">Error: {html_module.escape(str(e))}</div>', is_html=True)
    set_status(False)
    send_btn.disabled = False

send_btn.on_click(on_send)

display(HTML("""<script>
require(['jquery'], function($) {
  setTimeout(function() {
    $('textarea[placeholder="Ask about orders, billing, products\u2026"]')
      .off('keypress.o2c').on('keypress.o2c', function(e) {
        if (e.which === 13 && !e.shiftKey) {
          e.preventDefault();
          $(this).closest('.widget-hbox').find('button').first().click();
        }
      });
  }, 2500);
});
</script>"""))


# ── LAYOUT ────────────────────────────────────────────────────────────────────

legend_html = """<div class="o2c-legend">
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#1e88e5"></div>Customer</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#ff7043"></div>Order</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#66bb6a"></div>Line Item</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#f59e0b"></div>Product</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#ab47bc"></div>Invoice</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#26a69a"></div>Journal Entry</div>
  <div class="o2c-legend-item"><div class="o2c-legend-dot" style="background:#ef4444"></div>Highlighted</div>
</div>"""

# FIXED: graph_iframe wrapper uses position:relative so absolute iframe child fills it
graph_panel = widgets.VBox([
    widgets.HTML("""<div class="o2c-graph-topbar">
      <div class="o2c-graph-breadcrumb">Mapping / <strong>Order to Cash</strong></div>
      <div class="o2c-graph-actions">
        <button class="o2c-btn">Minimize</button>
        <button class="o2c-btn o2c-btn-dark">Hide Granular Overlay</button>
      </div></div>"""),
    widgets.HTML(legend_html),
    widgets.HTML(
        '<div style="position:relative;flex:1;min-height:0;width:100%;height:100%;overflow:hidden;">',
        layout=widgets.Layout(flex='0', height='0')
    ),
    graph_iframe,
    widgets.HTML('</div>', layout=widgets.Layout(flex='0', height='0')),
], layout=widgets.Layout(
    flex='0 0 75%',
    overflow='hidden',
    display='flex',
    flex_flow='column',
    min_height='0',
))

with chat_output:
    display(HTML("""<div class="o2c-msg ai">
      <div class="o2c-msg-label">DODGE AI</div>
      <div class="o2c-bubble-ai">
        <div style="font-weight:700;color:#111827;margin-bottom:6px;">
          Order-to-Cash Graph — Ready</div>
        <div style="color:#6b7280;font-size:11px;margin-bottom:8px;">
          Click any node to inspect its dataset fields.</div>
        <div style="border-top:1px solid #f3f4f6;padding-top:7px;
                    font-size:11px;color:#374151;line-height:1.8;">
          <strong>Try asking:</strong><br>
          · Trace order 740506<br>
          · Top products by billing<br>
          · Show broken flows<br>
          · Count all orders
        </div>
      </div></div>"""))

chat_panel = widgets.VBox([
    widgets.HTML("""<div class="o2c-chat-topbar">
      <div class="o2c-chat-eyebrow">Chat with Graph</div>
      <div class="o2c-chat-title">Order to Cash</div>
    </div>"""),
    status_w,
    chat_output,
    widgets.HBox(
        [chat_input, send_btn],
        layout=widgets.Layout(padding='10px 14px 14px', gap='8px', width='100%')
    )
], layout=widgets.Layout(
    flex='0 0 25%',
    min_width='280px',
    border_left='1px solid #e5e7eb',
    overflow='hidden',
    display='flex',
    flex_flow='column',
    min_height='0',
))

dashboard = widgets.HBox(
    [graph_panel, chat_panel],
    layout=widgets.Layout(
        width='100%', height='660px',
        border='1px solid #e5e7eb',
        border_radius='14px',
        overflow='hidden'
    )
)

# Build graph BEFORE display so it appears immediately
print("Building graph visualization…")
build_and_save_pyvis(G, GRAPH_INIT)
inject_graph_into_widget(GRAPH_INIT)
print("✓ Graph ready")

display(dashboard)